name: tabula-java
title: Tabula-Java
version: '1.0.5'
summary: Tabula-Java helps you liberate data tables trapped inside PDF files.
description: |
  tabula-java is a command line application that helps you to liberate data tables trapped inside PDF files.

  If you prefer an application with a user interface you can try https://snapcraft.io/tabula

  Visit https://github.com/tabulapdf/tabula-java for more information.

  Use 
     tabula-java --help
  to get more information.

  Please note that you need to use the command "tabula-java" instead of "tabula"
base: core20  
grade: stable 
confinement: strict
architectures: [amd64]
compression: lzo
license: MIT
environment:
  JAVA_HOME: $SNAP/usr/lib/jvm/java-8-openjdk-amd64/bin
  PATH: $SNAP/usr/lib/jvm/java-8-openjdk-amd64/bin:$PATH

apps:
  tabula-java:
    command: tabula.sh
    plugs:
      - removable-media
      - home
      - optical-drive

parts:
  get-jar:
    plugin: nil 
    build-packages:
      - wget
    override-build: |
      wget https://github.com/tabulapdf/tabula-java/releases/download/v1.0.5/tabula-1.0.5-jar-with-dependencies.jar
      cp tabula-1.0.5-jar-with-dependencies.jar $SNAPCRAFT_PART_INSTALL/tabula-1.0.5-jar-with-dependencies.jar
    override-prime: |
        snapcraftctl prime
        echo 'java -jar $SNAP/tabula-1.0.5-jar-with-dependencies.jar "$@"' > tabula.sh
        chmod +x tabula.sh
        
        rm -rf $SNAPCRAFT_PRIME/usr/lib/jvm/java-11-openjdk-amd64
  packages:
    plugin: nil
    stage-packages:  
      - openjdk-8-jre
      - ca-certificates
      - ca-certificates-java
    build-packages:  
      - ca-certificates
      - ca-certificates-java 
