name: tabula-java
title: Tabula-Java
version: '1.0.5'
summary: Tabula-Java helps you liberate data tables trapped inside PDF files.
description: |
  tabula-java provides a command line application:
  
  usage: tabula-java [-a <AREA>] [-b <DIRECTORY>] [-c <COLUMNS>] [-f <FORMAT>]
       [-g] [-h] [-i] [-l] [-n] [-o <OUTFILE>] [-p <PAGES>] [-r] [-s
       <PASSWORD>] [-t] [-u] [-v]

       Tabula helps you extract tables from PDFs

       -a,--area <AREA>           -a/--area = Portion of the page to analyze.
                                  Example: --area 269.875,12.75,790.5,561.
                                  Accepts top,left,bottom,right i.e. y1,x1,y2,x2
                                  where all values are in points relative to the
                                  top left corner. If all values are between
                                  0-100 (inclusive) and preceded by '%', input
                                  will be taken as % of actual height or width
                                  of the page. Example: --area %0,0,100,50. To
                                  specify multiple areas, -a option should be
                                  repeated. Default is entire page
       -b,--batch <DIRECTORY>     Convert all .pdfs in the provided directory.
       -c,--columns <COLUMNS>     X coordinates of column boundaries. Example
                                  --columns 10.1,20.2,30.3. If all values are
                                  between 0-100 (inclusive) and preceded by '%',
                                  input will be taken as % of actual width of
                                  the page. Example: --columns %25,50,80.6
       -f,--format <FORMAT>       Output format: (CSV,TSV,JSON). Default: CSV
       -g,--guess                 Guess the portion of the page to analyze per
                                  page.
       -h,--help                  Print this help text.
       -i,--silent                Suppress all stderr output.
       -l,--lattice               Force PDF to be extracted using lattice-mode
                                  extraction (if there are ruling lines
                                  separating each cell, as in a PDF of an Excel
                                  spreadsheet)
       -n,--no-spreadsheet        [Deprecated in favor of -t/--stream] Force PDF
                                  not to be extracted using spreadsheet-style
                                  extraction (if there are no ruling lines
                                  separating each cell)
       -o,--outfile <OUTFILE>     Write output to <file> instead of STDOUT.
                                  Default: -
       -p,--pages <PAGES>         Comma separated list of ranges, or all.
                                  Examples: --pages 1-3,5-7, --pages 3 or
                                  --pages all. Default is --pages 1
       -r,--spreadsheet           [Deprecated in favor of -l/--lattice] Force
                                  PDF to be extracted using spreadsheet-style
                                  extraction (if there are ruling lines
                                  separating each cell, as in a PDF of an Excel
                                  spreadsheet)
       -s,--password <PASSWORD>   Password to decrypt document. Default is empty
       -t,--stream                Force PDF to be extracted using stream-mode
                                  extraction (if there are no ruling lines
                                  separating each cell)
       -u,--use-line-returns      Use embedded line returns in cells. (Only in
                                  spreadsheet mode.)
       -v,--version               Print version and exit.
base: core20  
grade: stable 
confinement: strict
architectures: [amd64]
compression: lzo
license: MIT
environment:
  PATH: $SNAP/usr/lib/jvm/java-8-openjdk-amd64/bin:$PATH

apps:
  tabula-java:
    command: tabula.sh
#    extensions: [gnome-3-38]
#    plugs:
#      - network
#      - network-bind

  tabula-link:
    command: tabula-link.sh
    desktop: $SNAPCRAFT_PROJECT_DIR/tabula-desktop/tabula.desktop
    extensions: [gnome-3-38]
#   plugs:
#     - network
#     - network-bind

parts:
  get-jar:
    plugin: nil 
    override-pull: |
      wget https://github.com/tabulapdf/tabula-java/releases/download/v1.0.5/tabula-1.0.5-jar-with-dependencies.jar
    #override-build: |
    #  cp tabula-1.0.5-jar-with-dependencies.jar $SNAPCRAFT_PART_INSTALL/tabula-1.0.5-jar-with-dependencies.jar

  get-desktop:
    plugin: dump
    source: https://github.com/digidigital/tabula-java-snap/raw/main/tabula-desktop.zip
    source-type: zip
  packages:
    plugin: nil
    stage-packages:  
      - openjdk-8-jre
      - ca-certificates
      - ca-certificates-java
      - wget
    build-packages:
      - openjdk-8-jre
      - ca-certificates
      - ca-certificates-java
    override-prime: |
      snapcraftctl prime
      echo 'java -jar $SNAP/tabula-1.0.5-jar-with-dependencies.jar "$@"' > tabula.sh
      chmod +x tabula.sh
      
      echo 'xdg-open https://github.com/tabulapdf/tabula-java' > tabula-link.sh
      chmod +x tabula-link.sh
